version: '3'

services:
  mysql:
    container_name: mybonsaiapi-mysql
    image: mysql:8
    ports:
      - "3333:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    command: ["--default-authentication-plugin=mysql_native_password"]

  rabbitmq:
    container_name: mybonsaiapi-rabbitmq
    image: 'rabbitmq:3.7-management'
    restart: unless-stopped
    ports:
      - 5603:5672
      - 8009:15672
    environment:
      - RABBITMQ_DEFAULT_USER=mybonsaiapi
      - RABBITMQ_DEFAULT_PASS=mybonsaiapi

  nginx:
    container_name: mybonsaiapi-nginx
    image: nginx:1.15-alpine
    restart: unless-stopped
    ports:
      - "8003:80"
    volumes:
      - .:/app:delegated
      - ./etc/infrastructure/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  php:
    container_name: mybonsaiapi-php_ddd_skeleton-php
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "9099:9001"
    volumes:
      - .:/app:delegated
    env_file:
      - .env
    depends_on:
      - mysql
      - rabbitmq
